scripts:
  - scripts/**/*
  
scenes:
  - scripts/scenes/**/*

game:
  - scripts/game/**/*
  
assets:
  - images/**/*
  
sounds:
  - sounds/**/*

automation:
  - .github/**/*
  
documentation:
  - *.md
  
test:
  - scripts/**/*.spec.js
